### ISSUE TITLE
AttributeError: module 'george.kernels' has no attribute 'DeltaKernel'

### ISSUE THREAD

**Issue by sublimationAC** [maxc01/addtree#2]
Hi, thanks for your project.
I encounter a problem when running your project.

***
Traceback (most recent call last):
  File "addtree_jenatton_small.py", line 132, in <module>
    main()
  File "addtree_jenatton_small.py", line 67, in main
    ker = build_addtree(root)
  File "...../addtree/addtree/kernel_utils.py", line 11, in build_addtree
    kd = K.DeltaKernel(ndim=obs_dim, axes=node.bfs_index)
AttributeError: module 'george.kernels' has no attribute 'DeltaKernel'
***
I also cannot find 'DeltaKernel' from https://github.com/search?q=repo%3Amaxc01%2Fgeorge%20DeltaKernel&type=code.

Best regards

**Comment by maxc01** [comment]
hi @sublimationAC , I have updated the readme  and some util files for easier setup using conda:
```
conda create -n add python=3.11
conda activate add
conda install -y -c conda-forge libstdcxx-ng
conda install -y -c anaconda pyyaml jinja2 numpy scipy pybind11
git clone https://github.com/maxc01/addtree
cd addtree
pip install .
```
It should work now. Let me know if it does not work for you.

**Comment by sublimationAC** [comment]
Thanks for your reply. It works for me.
